# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH="$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
# Overwrite default '%'/'#' which zsh uses to mark a partial line
export PROMPT_EOL_MARK=''

ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#c0c0c0"
HIST_IGNORE_SPACE=true

plugins=(
    aliases
    aws
    terraform
    git
    git-auto-fetch
    python
    zsh-syntax-highlighting
    zsh-autosuggestions
    kubectl
    last-working-dir
    ssh-agent
    z
)

# manpager dracula
export MANPAGER="/usr/bin/less -s -M +Gg"
export LESS_TERMCAP_mb=$'\e[1;31m'      # begin bold
export LESS_TERMCAP_md=$'\e[1;34m'      # begin blink
export LESS_TERMCAP_so=$'\e[01;45;37m'  # begin reverse video
export LESS_TERMCAP_us=$'\e[01;36m'     # begin underline
export LESS_TERMCAP_me=$'\e[0m'         # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'         # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'         # reset underline
export GROFF_NO_SGR=1                   # for konsole

[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

# emacs keybinding
bindkey -e

# Use McFly for advanced shell history search, https://github.com/cantino/mcfly
if command -v mcfly &>/dev/null; then
    eval "$(mcfly init zsh)"
    export MCFLY_RESULTS=20
    export MCFLY_RESULTS_SORT=LAST_RUN
fi

# You may need to manually set your language environment
export LANG=de_DE.UTF-8

# Do menu-driven completion
zstyle ':completion:*' menu select

# autocomplete for kubectl-ns / kubectl-ctx
autoload -U compinit && compinit

[[ ! -f "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"

# custom aliases and function
if [ -d "$HOME/.helper" ]; then
    for f in $(ls -l $HOME/.helper | awk '{print $NF}' | grep -E "(alias|function)"); do
        source "$HOME/.helper/$f"
    done
else
    echo "$HOME/.helper not found, setup alias and functions failed!"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
